### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by johngarg** [algernon/adderall#17]
After a fresh install of adderall I get the following error at the REPL after importing everything from `adderall.dsl` as per the example in the README

```
=> (import [adderall.dsl [*]])
Traceback (most recent call last):
  File "stdin-13d9f4ed2fba76e7292f4eef6fccb574c1d68064", line 1, in <module>
    (import [adderall.dsl [*]])
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/adderall/internal.hy", line 26, in defmacro_alias
    (.append ret
hy.errors.HyMacroExpansionError:
  File "/usr/local/lib/python3.7/site-packages/adderall/dsl.hy", line 96
    (defmacro-alias [run1 run¹] [vars &rest args]
  "Return a single result from `run` (i.e. `n` set to `1`).

See `run`."
  `(first (run 1 ~vars ~@args)))
    ^
expanding macro defmacro-alias
  AttributeError: 'HyExpression' object has no attribute 'append'
```

I'm running hy 0.17.0+140.ge6d6a02 and Python 3.7.6 on macOS Mojave 10.14.4.

**Comment by brandonwillard** [comment]
You're seeing the issue described in https://github.com/hylang/hy/issues/1869.  `adderall` needs to be updated for more recent version of Hy.  In the meantime, try using a version of Hy that precedes https://github.com/hylang/hy/pull/1804.
